# Generated by Django 5.1.3 on 2024-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "issuer",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("date", models.CharField(max_length=255)),
                ("last_price", models.CharField(max_length=255)),
                ("max", models.CharField(max_length=255)),
                ("min", models.CharField(max_length=255)),
                ("average", models.CharField(max_length=255)),
                ("percent_change", models.CharField(max_length=255)),
                ("quantity", models.CharField(max_length=255)),
                ("best_trade", models.CharField(max_length=255)),
                ("total_trade", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "stock_prices",
            },
        ),
    ]
