# Generated by Django 5.1.3 on 2024-12-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("last_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("average", models.DecimalField(decimal_places=2, max_digits=10)),
                ("percent_change", models.DecimalField(decimal_places=2, max_digits=5)),
                ("quantity", models.IntegerField()),
                ("best_trade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_trade", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "db_table": "stock_prices",
                "unique_together": {("issuer", "date")},
            },
        ),
    ]
