# Generated by Django 5.1.3 on 2024-12-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mkd_stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="average",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="best_trade",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="date",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="last_price",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="max",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="min",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="percent_change",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="total_trade",
            field=models.CharField(max_length=255),
        ),
    ]
